pipeline {
    agent any

    stages {
    //     stage('Hello') {
    //         steps {
    //             echo 'Hello World'
    //             sh 'pwd'
    //         }
    //     }

        stage('Build Image') {
            steps {
                sh '''
                   cd Cat && docker build -t gexin7648/cat:JR10 .
                   cd ../helloworld && docker build -t gexin7648/helloworld:JR10 .
                   cd ../web-nginx && docker build -t gexin7648/mynginx:JR10 .
                   docker tag gexin7648/cat:JR10 gexin7648/cat:latest
                   docker tag gexin7648/helloworld:JR10 gexin7648/helloworld:latest
                   docker tag gexin7648/mynginx:JR10 gexin7648/mynginx:latest
                   docker images
		        '''
            }
        }

    //     stage('Push Image') {
    //         steps {
    //             withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'PSWD', usernameVariable: 'USER')]) {
    //                 sh """                        
    //                     docker login -u $USER -p $PSWD
    //                     for img in gexin7648/cat:JR10 gexin7648/cat:latest gexin7648/helloworld:JR10 gexin7648/helloworld:latest \
    //                            gexin7648/mynginx:JR10 gexin7648/mynginx:latest; \
    //                     do docker push \$img; done;
    //                 """
    //             }

    //         }
    //     }

        stage('Deploy Service') {
            steps {
                sh '''
                    docker-compose down
                    docker-compose up -d
                    docker-compose ps
                '''
            }
        }

    }
}